[zep noup][tf-m-test] ARMCLANG.cmake: Remove -fshort-enums and -fshort-wchar options
When RTX and NS are built without the -fshort options,
a linking error appears:
Error: L6242E: Cannot link object xyz.o as its attributes are
incompatible with the image attributes.
   ... wchart-16 clashes with wchart-32.
   ... packed-enum clashes with enum_is_int.

Remove those -fshort flags while other other components
are also built without such flags.

Signed-off-by: Nicola Mazzucato <nicola.mazzucato@arm.com>